# Generated by Django 4.2.11 on 2024-04-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('can_reservation_time', models.CharField(blank=True, max_length=255, null=True)),
                ('can_reservation_period', models.PositiveIntegerField(default=0)),
                ('end_reservation_day', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_day_for_week', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_day_for_day', models.CharField(blank=True, max_length=255, null=True)),
                ('today_reservation_limit', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('line_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('picture_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('fix_time', models.CharField(blank=True, max_length=255, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('line_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.lineuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('fix_time', models.CharField(blank=True, max_length=255, null=True)),
                ('fix_time_delete', models.CharField(blank=True, max_length=255, null=True)),
                ('fix_time_cancel', models.BooleanField(default=False)),
                ('flex_time', models.CharField(blank=True, max_length=255, null=True)),
                ('common_setting_id', models.PositiveIntegerField(default=0)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffSchedule', to='mainapp.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffCommonSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('fix_time', models.CharField(blank=True, max_length=255, null=True)),
                ('fix_time_delete', models.CharField(blank=True, max_length=255, null=True)),
                ('fix_time_cancel', models.BooleanField(default=False)),
                ('flex_time', models.CharField(blank=True, max_length=255, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffCommonSetting', to='mainapp.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
