# Generated by Django 4.2.11 on 2024-05-20 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffschedule',
            name='date_check',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 9, 55, 3, 682176)),
        ),
    ]
