# Generated by Django 4.2.11 on 2024-05-20 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_staffschedule_date_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffschedule',
            name='date_check',
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 10, 37, 59, 928877)),
        ),
    ]
