# Generated by Django 4.2.11 on 2024-05-21 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_staffschedule_date_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 16, 25, 51, 642349)),
        ),
    ]
