# Generated by Django 4.2.11 on 2024-05-21 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_staffschedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 1, 36, 19, 318127)),
        ),
    ]
