# Generated by Django 4.2.11 on 2024-05-23 04:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_staffschedule_date_takeleave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeleave',
            name='line_user',
        ),
        migrations.AddField(
            model_name='takeleave',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takeLeave', to='mainapp.staff'),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 12, 16, 0, 779918)),
        ),
    ]
