# Generated by Django 4.2.11 on 2024-05-23 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_takeleave_line_user_takeleave_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='break_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='work_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 14, 27, 27, 25906)),
        ),
    ]
