# Generated by Django 4.2.11 on 2024-05-23 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_adminsetting_break_time_adminsetting_work_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsetting',
            name='end_reservation_day',
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 22, 55, 40, 783940)),
        ),
    ]
