# Generated by Django 4.2.11 on 2024-05-26 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_adminsetting_end_reservation_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeleave',
            name='total_hour',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='takeleave',
            name='total_minute',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 18, 52, 5, 598791)),
        ),
    ]
