# Generated by Django 4.2.11 on 2024-05-31 08:28

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_lineuser_become_staff_time_alter_staffschedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineuser',
            name='become_staff_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 28, 7, 336319)),
        ),
    ]
