# Generated by Django 4.2.11 on 2024-06-04 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_lineuser_become_staff_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 22, 20, 9, 575704)),
        ),
    ]
