# Generated by Django 4.2.11 on 2024-06-04 14:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_staffschedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineuser',
            name='become_admin_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 22, 21, 9, 711534)),
        ),
    ]
