# Generated by Django 4.2.11 on 2024-06-05 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_lineuser_become_admin_time_alter_staffschedule_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takeleave',
            old_name='is_reviewed',
            new_name='is_approved',
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 15, 20, 51, 247403)),
        ),
    ]
