# Generated by Django 4.2.11 on 2024-06-05 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_rename_is_reviewed_takeleave_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='fix_time',
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 23, 31, 9, 121824)),
        ),
    ]
