# Generated by Django 4.2.11 on 2024-06-06 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_remove_staff_fix_time_alter_staffschedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeleave',
            name='approve_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
