# Generated by Django 4.2.11 on 2024-06-06 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_takeleave_approve_date_alter_staffschedule_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchInorOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('punch_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('punch_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punchInorOut', to='mainapp.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
