# Generated by Django 4.2.11 on 2024-06-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_punchinorout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punchinorout',
            old_name='punch_in',
            new_name='punch_in_time',
        ),
        migrations.RenameField(
            model_name='punchinorout',
            old_name='punch_out',
            new_name='punch_ou_timet',
        ),
        migrations.AddField(
            model_name='punchinorout',
            name='is_punch_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='punchinorout',
            name='is_punch_out',
            field=models.BooleanField(default=False),
        ),
    ]
