# Generated by Django 4.2.11 on 2024-06-07 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_rename_punch_in_punchinorout_punch_in_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punchinorout',
            old_name='punch_ou_timet',
            new_name='punch_out_time',
        ),
    ]
