# Generated by Django 4.2.11 on 2024-06-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_punchinorout_is_take_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchinorout',
            name='is_take_leave_approve',
            field=models.BooleanField(default=False),
        ),
    ]
