# Generated by Django 4.2.11 on 2024-06-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_adminsetting_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
