# Generated by Django 4.2.11 on 2024-06-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_adminsetting_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
