# Generated by Django 4.2.11 on 2024-05-16 08:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('line', '0002_rename_booking_service_reservation_add_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_check',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 16, 9, 32, 213077)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='staff_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffSchedule', to='mainapp.staffschedule'),
        ),
    ]
