# Generated by Django 4.2.11 on 2024-05-20 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0003_reservation_date_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_check',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 9, 55, 3, 805588)),
        ),
    ]
