# Generated by Django 4.2.11 on 2024-05-20 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0004_alter_reservation_date_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_check',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 10, 38, 0, 115900)),
        ),
    ]
