# Generated by Django 4.2.11 on 2024-05-21 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0006_remove_reservation_date_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 1, 36, 19, 401624)),
        ),
    ]
