# Generated by Django 4.2.11 on 2024-05-23 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0008_remove_reservation_is_full_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 11, 30, 28, 813020)),
        ),
    ]
