# Generated by Django 4.2.11 on 2024-05-26 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_takeleave_total_hour_takeleave_total_minute_and_more'),
        ('line', '0012_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 18, 52, 5, 726986)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='staff_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='mainapp.staffschedule'),
        ),
    ]
