# Generated by Django 4.2.11 on 2024-06-17 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0028_remove_order_amount_alter_reservation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 11, 54, 16, 971543)),
        ),
    ]
