# Generated by Django 4.2.11 on 2024-06-27 01:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0039_order_address_order_pickup_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 9, 33, 42, 817271)),
        ),
    ]
