# Generated by Django 4.2.11 on 2024-06-27 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0040_order_transaction_time_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 12, 13, 47, 272322)),
        ),
    ]
